apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortenurl-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortenurl
  template:
    metadata:
      labels:
        app: shortenurl
    spec:
      containers:
        - name: shortenurl
          image: silkflo/shortenurl
          env:
            - name: MONGO_URI
              value: 'mongodb://shortenurl-mongo-srv:27017/urldb'
---
apiVersion: v1
kind: Service
metadata:
  name: shortenurl-srv
spec:
  selector:
    app: shortenurl
  ports:
    - name: shortenurl
      protocol: TCP
      port: 3000
      targetPort: 3000
