name: tests-shortenurl

on:
  pull_request:
    paths:
      - 'shortenurl/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd shortenurl && npm install && npm run test:ci
